### ISSUE TITLE
Considere the .gitignore file on search

### ISSUE THREAD

**Issue by tatosjb** [Cmacu/gotoanything#2]
This extention does not ignores the ignored paths. It may cause some performance issues

**Comment by Cmacu** [comment]
Which ignore paths are you referring to?
The extension is using the `files.exclude` and `search.exclude` from the VSCode settings to determine the ignore paths when searching files.

**Comment by tatosjb** [comment]
But you dont think that is a good thing, add ignores on .gitignore?

**Comment by Cmacu** [comment]
There are 2 settings in VSCode called `Search: Use Ignore files` (`search.useIgnoreFiles`) and `Search: Use Global Ignore Files` (search.useGlobalIgnoreFiles`).
Let me know, if this doesn't solve your issue.

**Comment by tatosjb** [comment]
Usually the projects have different ignore paths, then, if i depend on ignore files or global ignore files on text editor. I'll probably add lots of register on those configurations.

Just to give you one example, one of the projects that I work on, have 23 lines on .gitignore file. Becouse those files/folders are automatically generated. 

Then if I go to another projetct I have to configure another bunch of paths.

I don't know if you get my point, let me know if I not be as clear as I wanted

**Comment by Cmacu** [comment]
I think I understand what you are saying, I use git ignore files too.
That's what the first VSCode setting (`search.useIgnoreFiles`) from my previous response is used for. From the documentation: 

> Controls whether to use `.gitignore` and `.ignore` files when searching for files

This setting is respected by the extension. Please try enabling it and let me know, if it doesn't help. I may need a more specific example since this worked for me in few projects I just tested.

**Comment by beinginorbit** [comment]
I have `search.useIgnoreFiles` and this extension does not respect that setting properly, `.env.*.local` is in my .gitignore.
![image](https://user-images.githubusercontent.com/2807897/75585953-e4b5a780-5a38-11ea-86da-34d791d02408.png)

**Comment by Cmacu** [comment]
This is resolved in 0.4.0. Reopen, if the issue persists.

**Comment by beinginorbit** [comment]
@Cmacu works much much faster now thank you!
